export const University = [
  {
    id: 1,
    country: "United States",
    university_name: "Academy of Art University",
    master_agents: "KC",
  },
  {
    id: 2,
    country: "New Zealand",
    university_name: "Adelphi University",
    master_agents: "CANAM",
  },
  {
    id: 3,
    country: "Germany",
    university_name: "American University",
    master_agents: "KC",
  },
  {
    id: 4,
    country: "United States",
    university_name: "Florida National University",
    master_agents: "KC",
  },
  {
    id: 5,
    country: "Australia",
    university_name: "Arizona State University",
    master_agents: "KC",
  },
  {
    id: 6,
    country: "Ireland",
    university_name: "Arkansas State University",
    master_agents: "CANAM",
  },
  {
    id: 7,
    country: "Italy",
    university_name: "Ashland University",
    master_agents: "Me",
  },
  {
    id: 8,
    country: "United States",
    university_name: "Bay State College",
    master_agents: "KC",
  },
  {
    id: 9,
    country: "United States",
    university_name: "Baylor University",
    master_agents: "CANAM",
  },
  {
    id: 10,
    country: "United States",
    university_name: "Berkeley College",
    master_agents: "KC",
  },
  {
    id: 11,
    country: "United States",
    university_name: "Bowling Green State University",
    master_agents: "CANAM",
  },
  {
    id: 12,
    country: "United States",
    university_name: "Bradley University",
    master_agents: "KAAISER",
  },
  {
    id: 13,
    country: "United States",
    university_name: "California Baptist University",
    master_agents: "Anmol",
  },
  {
    id: 14,
    country: "United States",
    university_name: "California College of Music",
    master_agents: "Manoj",
  },
  {
    id: 15,
    country: "United States",
    university_name: "Otis College of Art and Design(OTIS)",
    master_agents: "Meenu Dada",
  },
  {
    id: 16,
    country: "United States",
    university_name: "California International Business University",
    master_agents: "Anmol",
  },
  {
    id: 17,
    country: "United States",
    university_name: "California Lutheran University",
    master_agents: "KC",
  },
];
